// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InquirySubscriptionController from "./inquiry_subscription_controller"
application.register("inquiry-subscription", InquirySubscriptionController)

import MapController from "./map_controller"
application.register("map", MapController)

// import PopoverController from "./popover_controller"
// application.register("popover", PopoverController)

import SearchBarController from "./search_bar_controller"
application.register("search-bar", SearchBarController)

// import TooltipController from "./tooltip_controller"
// application.register("tooltip", TooltipController)
